//! Generate `src/tokens_generated.rs` from `tokens.toml`.
//!
//! Each `[section]` becomes a Rust submodule under `tokens`.  Within a
//! section, string entries become `pub const NAME: &str = "...";`, and
//! numeric entries become `pub const NAME: f64 = ...;` (or `u32` for integer
//! weights — autodetected by parsing the value).

use std::env;
use std::fs;
use std::path::PathBuf;
use toml::Value;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let in_path  = PathBuf::from(&crate_dir).join("tokens.toml");
    let out_path = PathBuf::from(&crate_dir).join("src/tokens_generated.rs");

    println!("cargo:rerun-if-changed={}", in_path.display());

    // EXE icon embedding lives in the application's own build.rs — see
    // `uzor_framework::utils::resource::embed_icon_and_manifest`.  The
    // framework crate itself ships no default .ico because end-user apps
    // supply their own branding asset.  Examples that need a process icon
    // place their .ico in `examples/assets/` and embed it via the example's
    // own build script (per-example build.rs is not supported by cargo, so
    // examples either go without the embedded .ico or move into a separate
    // bin crate).

    let raw = fs::read_to_string(&in_path).unwrap_or_else(|e| {
        panic!("failed to read {}: {}", in_path.display(), e);
    });
    let parsed: Value = toml::from_str(&raw).unwrap_or_else(|e| {
        panic!("invalid TOML in {}: {}", in_path.display(), e);
    });

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs from tokens.toml — do not edit.\n\n");

    if let Value::Table(root) = parsed {
        for (section, value) in root {
            emit_section(&mut out, &section, value);
        }
    } else {
        panic!("tokens.toml top level must be a TOML table");
    }

    fs::write(&out_path, out).unwrap_or_else(|e| {
        panic!("failed to write {}: {}", out_path.display(), e);
    });
}

fn emit_section(out: &mut String, name: &str, value: Value) {
    let table = match value {
        Value::Table(t) => t,
        other => panic!("section `{}` must be a table, got {:?}", name, other),
    };

    // Sections may be nested (e.g. `colors.surface`).  Replace `.` with `_`
    // for the module name.
    let mod_name = name.replace('.', "_");
    out.push_str(&format!("pub mod {} {{\n", mod_name));

    // Buckets: nested-table entries become sub-mods, scalars become consts.
    let mut nested: Vec<(String, Value)> = Vec::new();
    let mut scalars: Vec<(String, Value)> = Vec::new();
    for (k, v) in table {
        if matches!(v, Value::Table(_)) {
            nested.push((k, v));
        } else {
            scalars.push((k, v));
        }
    }

    for (k, v) in scalars {
        emit_scalar(out, &k, v);
    }
    for (k, v) in nested {
        emit_section(out, &k, v);
    }

    out.push_str("}\n\n");
}

fn emit_scalar(out: &mut String, name: &str, value: Value) {
    match value {
        Value::String(s) => {
            out.push_str(&format!("    pub const {}: &str = {:?};\n", name, s));
        }
        Value::Integer(i) => {
            out.push_str(&format!("    pub const {}: u32 = {};\n", name, i));
        }
        Value::Float(f) => {
            // Always emit with explicit decimal so it parses as f64.
            let s = if f.fract() == 0.0 { format!("{:.1}", f) } else { format!("{}", f) };
            out.push_str(&format!("    pub const {}: f64 = {};\n", name, s));
        }
        Value::Boolean(b) => {
            out.push_str(&format!("    pub const {}: bool = {};\n", name, b));
        }
        other => {
            panic!("unsupported value type for `{}`: {:?}", name, other);
        }
    }
}
